require:
  - rubocop-rspec
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - bin/*
    - "*.gemspec"
    - Rakefile
    - vendor/**/*.rb
    - gemfiles/vendor/bundle/**/*

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Naming/MethodParameterName:
  AllowedNames:
    - 'to'
    - 'at'
    - 'on'
    - 'id'
    - 'in'
    - 'as'

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*_spec.rb


